### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by MiguelHigueraDev** [MiguelHigueraDev/discord-bouncer-bot#1]
# Cache guild channels

- [X] Cache guild channels on session start so database is hit only once.

# Add Readme

- [X] Add a README file with images to showcase the bot

# Better exception handling

- [X] Improve error messages 
- Even though task has been completed, there could be done more work on this later.

# Refactor

- [x] Refactor some parts of the code to better separate concerns
